### ISSUE TITLE
add artifact coordinates to README

### ISSUE THREAD

**Issue by anewton1998** [snowe2010/pretty-print#13]
This is an excellent library.

For new users, it might be helpful to add simple instructions for adding the dependency to Gradle such as `compile( "com.tylerthrailkill.helpers:pretty-print:2.0.0" )`

**Comment by snowe2010** [comment]
That is a good idea. I had thought about it, but thought linking to jcenter would be enough. I actually think it would be best to specify it without the version. Something like `implementation("com.tylerthrailkill.helpers:pretty-print:$prettyPrintVersion")` just so people don't try to use an older version of the library, and less maintenance for me. 😂
