### ISSUE TITLE
where is 2.0.2 published?

### ISSUE THREAD

**Issue by sergeych** [snowe2010/pretty-print#21]
can't add it with maven, and last known 1.9.2 seems to be different from the usage seen in readme.

**Comment by snowe2010** [comment]
Hi! You can click on the badge in the Readme to get to the published artifact. [Here it is on Bintray](https://bintray.com/snowe/maven/Pretty-Print/2.0.2) and [here it is in Maven Central](https://search.maven.org/artifact/com.tylerthrailkill.helpers/pretty-print/2.0.2/jar)!

I'm not sure what you mean by 1.9.2 though. It also appears I have a copy and paste typo in my readme that I need to fix, in regards to the gradle example.

**Comment by snowe2010** [comment]
Newer versions are now also published on [Github Packages](https://github.com/snowe2010/pretty-print/packages) along with [Bintray](https://bintray.com/snowe/maven/Pretty-Print) and [Maven Central](https://search.maven.org/artifact/com.tylerthrailkill.helpers/pretty-print).
