### ISSUE TITLE
Kotlin extentions

### ISSUE THREAD

**Issue by ronjunevaldoz** [snowe2010/pretty-print#31]
I would like to request a feature, to add kotlin extensions like below example.

```kotlin
val hello = World()
hello.pp()
```

**Comment by snowe2010** [comment]
@ronjunevaldoz Hi, thanks for creating an issue. This feature currently exists. It's detailed in the first paragraph in the readme, and you can view the code [here](https://github.com/snowe2010/pretty-print/blob/master/src/main/kotlin/com/tylerthrailkill/helpers/prettyprint/PrettyPrint.kt#L36-L40). 

Let me know if you have any questions, or if the documentation isn't clear enough!

**Comment by ronjunevaldoz** [comment]
> @ronjunevaldoz Hi, thanks for creating an issue. This feature currently exists. It's detailed in the first paragraph in the readme, and you can view the code [here](https://github.com/snowe2010/pretty-print/blob/master/src/main/kotlin/com/tylerthrailkill/helpers/prettyprint/PrettyPrint.kt#L36-L40).
> 
> Let me know if you have any questions, or if the documentation isn't clear enough!

My bad, I didnt realize it

**Comment by ronjunevaldoz** [comment]
I really was looking for this kind of extension. I wanted to easily debug all my objects, also looking forward that this library would add a collapsable view, that I could easily plug n play.
