### ISSUE TITLE
String literals should always be surrounded with double quotes

### ISSUE THREAD

**Issue by ndon55555** [snowe2010/pretty-print#6]
In the tests, string literals are expected to be surrounded by double quotes when they are an element of a list or is a key or value in a map. However, when a string is the value of a field inside of an object, it is expected not to be surrounded by quotes when pretty printing.

e.g. list test
```
it("render a list of strings") {                 
    prettyPrint(listOf("a", "b", "c")) mapsTo """
        [                                        
          "a",                                   
          "b",                                   
          "c"                                    
        ]                                        
        """                                      
}                                                
```

e.g. map test
```
it("single key value pair") {                      
    prettyPrint(mapOf("key" to "value")) mapsTo """
    {                                              
      "key" -> "value"                             
    }                                              
    """                                            
}                                                  
```

e.g. object with string field test
```
it("two fields") {                             
    prettyPrint(SmallObject("a", 1)) mapsTo """
    SmallObject(                               
      field1 = a                              
      field2 = 1                               
    )                                          
"""                                            
}                                              
```

Is this an intentional decision?

**Comment by snowe2010** [comment]
Ah no this should not be happening! I wonder how I made that mistake. That's why you don't copy and paste tests! I'll have a fix out today. Thanks for the issue!

**Comment by snowe2010** [comment]
@ndon55555 how do you think this should be handled actually? For example, on line 186 of the MassiveObjectTest.kt, the string contains `"`. Should I wrap all strings in `"`? or wrap none of them? I don't want to perform escaping because I kind of want it to be a wysiwyg pretty printer.

**Comment by ndon55555** [comment]
@snowe2010 That's true, it does look hard to read if there are escaped quotes in the string. However, can't the same argument go for quoting strings inside collections? The elements, keys, and values in those can have escaped quotes, too. For example, `"\"john..doe\"@example.org"` would show up as `""john..doe"@example.org` in a pretty printed collection.

**Comment by snowe2010** [comment]
Yes, I was actually asking you if you thought I should remove all quotes around all strings or put quotes around all strings. I went with the latter, as it allows me to print the cycle detection string without making it seem like it's an actual string in the code (however unlikely that is)

**Comment by ndon55555** [comment]
Oh, gotcha. I should read more carefully

**Comment by snowe2010** [comment]
No worries. Thanks for the issues! I have hopefully improved the library to meet some of your expectations!
