### ISSUE TITLE
Test expectations not up to date with new features

### ISSUE THREAD

**Issue by ndon55555** [snowe2010/pretty-print#7]
In the naughty_strings.json, there are some strings whose lengths are greater than the specified wrapping width. They are not broken into multiline strings in naughty_string_printed.txt. This means that the current implementation of string wrapping shows as passing all tests when it should not be.

**Comment by snowe2010** [comment]
Yes! I'm glad you noticed this, as for the past week I've been trying to get unicode line breaking working! It's not an easy problem (I thought until today), but I should have a new release today to update this.

**Comment by snowe2010** [comment]
Just to explain why the tests work but the code seems to not work. Anywhere you see long lines in the naughty list and it's not breaking is due to it being a unicode code point other than `\u0020`. My release today should fix this.
