### ISSUE TITLE
Functional usage

### ISSUE THREAD

**Issue by ennioVisco** [snowe2010/pretty-print#96]
It would be nice if there was a pp() version that instead of directly printing returns the result as a string, so that it can be passed to alternative facilities (loggers and/or data structures used for later)

**Comment by snowe2010** [comment]
@ennioVisco `pp` has a parameter `writeTo` that defaults to `System.out`, but accepts any `Appendable`. You can pass your own `Appendable` to get the result you want. Would that work for you?

**Comment by ennioVisco** [comment]
@snowe2010 oh yes, that should work, please update the readme with this info 😄

**Comment by snowe2010** [comment]
oh, it's called `printStream` in the readme. I'll update that. Thank you!
